name: reusable-build-and-deploy
on:
  workflow_call:
    inputs:
      image_name:
        { description: "GHCR image (owner/name)", required: true, type: string }
      service_dir:
        {
          description: "Remote dir with compose.yaml",
          required: true,
          type: string,
        }
      context:
        {
          description: "Docker build context",
          required: false,
          type: string,
          default: ".",
        }
      dockerfile:
        {
          description: "Dockerfile path",
          required: false,
          type: string,
          default: "Dockerfile",
        }
      build_args:
        {
          description: "Extra build args (KEY=VAL,space-separated)",
          required: false,
          type: string,
          default: "",
        }
    secrets:
      DEPLOY_HOST: { required: true }
      DEPLOY_KEY: { required: true }
      TS_AUTHKEY: { required: true }

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & tag
        run: |
          docker build -t $REGISTRY/${{ inputs.image_name }}:$GITHUB_SHA .
          docker tag  $REGISTRY/${{ inputs.image_name }}:$GITHUB_SHA $REGISTRY/${{ inputs.image_name }}:latest

      - name: Push
        run: |
          docker push $REGISTRY/${{ inputs.image_name }}:$GITHUB_SHA
          docker push $REGISTRY/${{ inputs.image_name }}:latest

      - name: Start Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          umask 177
          cat > key.pem <<'KEY'
          ${{ secrets.DEPLOY_KEY }}
          KEY
          ssh-keyscan -T 10 ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: deploy
          key_path: key.pem
          script_stop: true
          debug: true
          script: |
            set -e
            cd ${{ inputs.service_dir }}
            docker pull ghcr.io/${{ inputs.image_name }}:latest
            docker compose up -d
            docker image prune -f
